from typing import Tuple, Dict, Any, List, Optional


def validate_input(forecast_data: Any) -> Tuple[bool, Optional[str]]:
    """
    Validates the structure of the incoming weather forecast JSON data.
    
    Args:
        forecast_data: Parsed JSON data to be validated.
        
    Returns:
        A tuple containing a boolean indicating validity, and an error message string if invalid.
    """
    if forecast_data is None:
        return False, "Input data is None."

    if not isinstance(forecast_data, list):
        return False, "Input data must be a JSON array."

    if len(forecast_data) == 0:
        return False, "Input array is empty."

    for i, entry in enumerate(forecast_data):
        if not isinstance(entry, dict):
            return False, f"Element at index [{i}] is not a JSON object."

        if not entry.get("location"):
            return False, f"Element at index [{i}] is missing or has empty 'location' field."

        if not entry.get("date"):
            return False, f"Element at index [{i}] is missing or has empty 'date' field."

        if "alerts" not in entry:
            return False, f"Element at index [{i}] is missing 'alerts' field."

    return True, None


def validate_gemini_response(response_data: Any) -> Tuple[bool, Optional[str]]:
    """
    Validates the structure of the JSON response generated by Gemini.
    
    Args:
        response_data: The parsed JSON object returned by the model.
        
    Returns:
        A tuple containing a boolean indicating validity, and an error message string if invalid.
    """
    if response_data is None:
        return False, "Gemini response is None."

    if not isinstance(response_data, dict):
        return False, "Response must be a JSON object."

    required_fields = ["location", "date", "highest_alert_level", "messages"]
    for field in required_fields:
        if field not in response_data:
            return False, f"Missing required field: '{field}'."
        if not response_data[field]:
            return False, f"Field '{field}' is empty or null."

    messages = response_data.get("messages", {})
    if not isinstance(messages, dict):
        return False, "Field 'messages' must be a JSON object."

    required_langs = {
        "vi": "Vietnamese",
        "thai": "Thai",
        "hmong": "Hmong"
    }
    
    for lang_key, lang_name in required_langs.items():
        if lang_key not in messages:
            return False, f"Missing {lang_name} translation (messages.{lang_key})."
        if not messages[lang_key] or not str(messages[lang_key]).strip():
            return False, f"{lang_name} translation (messages.{lang_key}) is empty."

    valid_levels = {"Red", "Orange", "Yellow", "Green"}
    if response_data["highest_alert_level"] not in valid_levels:
        return False, f"Invalid alert level: '{response_data['highest_alert_level']}'. Expected one of: {valid_levels}."

    return True, None
